/*
THIS IS INDEX OF THE COURSE 
EP 12 --> LEARN ABOUT HASHING 
EP13 --> LEARN ABOUT PREFIX SUM ON 1-D ARRAY
EP13b --> LEARN ABOUT PREFIX SUM ON 2-D ARRAY
EP14 --> GCDQ QUESTION ON PREFIX SUM FROM CODECHEF
EP15 --> A MEDIUM LEVEL QUESTION FROM HACKERRANK ON PREFIX SUM AND HASHING 

EP21---> learn about pairs 
EP21B --> LEARN A BREIF ABOUT VECTORS
EP22A --> LEARN ABOUT HOW TO NEST PAIR WITH VECTORS
EP22B --> LEARN ABOUT HOW TO CREATE AN ARRAY OF VECTORS
EP22C --> LEARN ABOUT HOW TO CREATE VECTORS OF VECTORS 
EP23 --> INTRODUCTION TO VECTOR AND ITREATOR
EP23B --> VECTOR OF PAIR
EP24 --> AUTO AND RANGE BASED LOOPS 
EP25 --> INTRODUCTION TO MAPS
EP25B --> PROBLEM OVER MAPS
EP26 --> INTRODUCTION TO UNORDERED MAPS
EP26B --> PROBLEM TO UNORDERED MAPS
EP27 --> INTRODUCTION TO SETS AND UNORDERED SET
EP27B --> PROBLEM ON UNORDERED SETS
EP27C --> INTRODUCTION TO MULTISET
EP28 --> PROBLEM ON MULTISET (MONK AND MAGICAL CHARACTERS)
EP29 --> LEARN ABOUT NESTING IN STL 
EP30 --> STACK AND QUEUES
EP31 ---> A QUESTION ON STACK IMPLEMENTION --> BALANCING BRACKETS 
EP32 -> STACK IMPLEMENTION --> NEXT GREATER ELEMENT 
EP33 -> STL SORT FUNTION 
EP34-> LEARN ABOUT COMPARATOR FUNTION 
EP35-> LEARN ABOUT UPPER BOUND AND LOWER BOUND 
EP36-> STL ALGORITHMS 
EP 37-> LAMBDA FUNTION AND STL ALGORITHMS
EP38 -> ADVANCED RECURSION AND BACK TRACKING --> PARANTHSIS MATCHING ->LEETCODE
EP 39 -> SUBSET GENERATION USING RECURSION 
EP40 - > BINARY SEARCH AND MONOTONIC FUNTIONS 
EP41 -> IMPLEMENTION OF UPPERBOUND AND LOWER BOUNND USING BINARY SEARCH 
EP42 -> NTH ROOT OF A NUMBER USING BINARY SEARCH 












*/