'use strict';
/**
 Javascript is a HIGH-LEVEL PROTOTYPE-BASED OBJECT ORIENTED MULTI-PARADIGM INTERPRETED OR JUST IN TIME COMPILED DYNAMIC SINGLE THREADED GARBAGE-COLLECTED programming language with FIRST CLASS FUNCTIONS and NON-BLOCKING EVENT LOOP CONCURRENCY MODEL. 
 */